Repository lordendbear/Sportsemblr.2, pull requests merged in 2018-03, with the labels that each got.

#1 Initial client setup
  README.md
  client/config/env.js
  client/config/jest/cssTransform.js
  client/config/jest/fileTransform.js
  client/config/paths.js
  client/config/polyfills.js
  client/config/webpack.config.dev.js
  client/config/webpack.config.prod.js
  client/config/webpackDevServer.config.js
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/scripts/build.js
  client/scripts/start.js
  client/scripts/test.js
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/registerServiceWorker.js
  client/yarn.lock
Labels: config

#2 Remove unnecessary readme
  README.md
Labels: docs

#3 Add link to summary
  README.md
Labels: docs

#4 Initial server setup
  server/api/index.js
  server/config.json
  server/config/db.js
  server/index.js
  server/lib/util.js
  server/middleware/index.js
  server/package.json
Labels: config

#31 Prepush hook on whole repo
  client/package.json
  client/scripts/test.js
  package.json
Labels: bug, config

#32 Redux init
  client/package.json
  client/src/App.js
  client/src/actions/actionTypes.js
  client/src/components/App.css
  client/src/components/App.js
  client/src/components/App.test.js
  client/src/index.js
  client/src/reducers/index.js
  client/src/reducers/initialState.js
  client/src/routes.js
  client/src/store/configureStore.js
Labels: config

#33 Server jwt
  server/api/auth/auth.controller.js
  server/api/auth/auth.routes.js
  server/api/auth/index.js
  server/api/index.js
  server/config/app.js
  server/config/passport.js
  server/index.js
  server/middleware/auth.js
  server/package.json
  server/utils/index.js
  server/utils/token-manager.js
Labels: enhancement

#38 Login client
  client/src/actions/actionTypes.js
  client/src/actions/authActions.js
  client/src/api/authApi.js
  client/src/components/App.css
  client/src/components/App.js
  client/src/components/auth/Login.js
  client/src/components/auth/Register.js
  client/src/components/layout/Navbar.js
Labels: enhancement

#42 Add fields to models
  docs/Models.md
Labels: config, docs

#44 Notifications
  client/src/actions/actionTypes.js
  client/src/actions/authActions.js
  client/src/actions/notificationActions.js
  client/src/actions/placeActions.js
  client/src/components/App.jsx
  client/src/components/common/Notification.jsx
  client/src/components/place/ManagePlace.jsx
  client/src/containers/Notification.jsx
  client/src/reducers/index.js
  client/src/reducers/initialState.js
  client/src/reducers/notificationReducer.js
Labels: enhancement

#45 Create event client
  client/package-lock.json
  client/package.json
  client/src/actions/actionTypes.js
  client/src/actions/eventActions.js
  client/src/actions/eventActions.test.js
  client/src/actions/placeActions.test.js
  client/src/api/eventApi.js
  client/src/components/App.jsx
  client/src/components/event/EditEvent.jsx
  client/src/containers/ManageEvent.jsx
  client/yarn.lock
Labels: enhancement

#49 Client places list
  client/src/actions/actionTypes.js
  client/src/actions/placeActions.js
  client/src/api/placeApi.js
  client/src/components/App.jsx
  client/src/components/event/EventShort.jsx
  client/src/components/place/PlaceShort.jsx
  client/src/components/place/PlacesList.jsx
  client/src/containers/place/PlacesList.jsx
  client/src/index.js
  client/src/reducers/placeReducer.js
Labels: enhancement
